blog/urls.py
from django.conf.urls import url,include
from . import views

app_name='blog'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^view/(?P<slug>[-\w]+)/$',views.view_post, name='view_post'),
	url(r'^category/(?P<slug>[-\w]+)/$',views.view_category, name='view_category'),
	url(r'^new$',views.post_new, name='post_new'),
	#url(r'accounts/', include('registration.backends.hmac.urls')),
	url(r'^post/(?P<slug>[-\w]+)$', views.post_edit, name='post_edit'),
	url(r'logout/$', views.logout_page,name='logout_page'),
	url(r'register/$',views.register_page,name='register_page'),
	url(r'search/$', views.search, name='search'),
	url(r'^follow/(?P<pk>[0-9]+)', views.follow,name='follow'),
	url(r'^unfollow/(?P<pk>[0-9]+)',views.unfollow, name='unfollow'),
	url(r'^login$', views.login, name='login'),
	#url(r'login/$', views.login_page, name='login_page'),
	]
#[^\.]       ?????
#study regular expressions again!

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    #url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$',views.default )
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models import permalink
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image
# Create your models here.

class Category(models.Model):
	title =models.CharField(max_length=100, db_index=True)
	slug =models.SlugField(max_length=100, db_index=True)
	#def __unicode__(self):
	#	return '%s' %self.title

	#@permalink
	#def get_absolute_url(self):
	#	return ('view_blog_category', None, {'slug':self.slug})

	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		super(Category, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

#Review this again!
class Profile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	birth_date=models.DateField(null=True, blank=True)
	followers=models.ManyToManyField(User,related_name='following',symmetrical=False)#list of followers


	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created :
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


class Blog(models.Model):
	title = models.CharField(max_length = 100, unique=True)
	slug = models.SlugField(max_length=100,unique = True)
	body = models.TextField()
	img=models.ImageField(upload_to='blog/blog/static/',null=True,help_text='Upload an image')
	posted =models.DateField(db_index = True, auto_now_add=True)
	category=models.ForeignKey('blog.Category', on_delete=models.CASCADE,default='1')
	date = models.DateTimeField(auto_now_add=True)
	update= models.DateTimeField(auto_now=True)
	author=models.ForeignKey(Profile,related_name='article',on_delete=models.CASCADE,default=1)

#revisit on_delete .
	#def __unicode__(self):
	#	return self.title

	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		super(Blog, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

	#@permalink
	#def get_absolute_url(self):
	#	return ('view_blog_post', None, {'slug':self.slug})

blog/forms.py
from django.forms import ModelForm
from django import forms
from blog.models import Blog
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class PostForm(ModelForm):

    class Meta:
        model = Blog
        fields = ['title','body','category']

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    first_name=forms.CharField(label='First Name', max_length=20)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())

    def clean_password2(self):
    	if 'password1' in self.cleaned_data:
    		password1=self.cleaned_data['password1']
    		password2=self.cleaned_data['password2']
    		if password1 == password2:
    			return password2
    	#raise forms.ValidationError('Passwords do not match')
    		else:
    			raise forms.ValidationError("passwords do not match")


    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        #raise forms.ValidationError('Username is already taken.')
        raise forms.ValidationError(('Username is already taken'), code='invalid')

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import PostForm,RegistrationForm
#from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Blog, Category,Profile
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,authenticate, login as auth_login, views as auth_views
#from django.contrib.auth import login as auth_login
#from app.forms import *
#from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.db.models import Q
from PIL import Image
import os
#Django.contrib.auth  ---------  authenticate() to authenticate if the specific user is logged in

@login_required
def index(request):
	#print request.user.username
	#a=list(Profile.objects.all())
	#print a.username   --------------   WRONG!
#	print a[0].user.username	----------- RIGHT!
	if request.GET:
		query=(request.GET.get("q"))
		#print query
		request.session['query']=query
		return redirect('blog:search')


	q=request.user
	#tr=authenticate(username='raghav',password='bitspilani')
	a=Profile.objects.get(user=q)
	#u=authenticate()

	list_following=list(q.following.all())
	l=len(list_following)

	context={'l':l,'list':list_following,'categories':Category.objects.all(),'followers':list(a.followers.all()),'posts':Blog.objects.all(), 'username':request.user.username,'user_profile':a}
	return render(request,'blog/index.html', context)

@login_required
def view_post(request, slug):
	context = {'post':get_object_or_404(Blog, slug=slug)}

	return render(request,'blog/view_post.html',context)


def view_category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	context = {'category':category, 'posts':Blog.objects.filter(category = category)}
	return render(request,'blog/view_category.html', context)

@login_required
def post_new(request):

	if request.method=='POST':
		form =PostForm(request.POST,request.FILES)
		#print "IS_VALID"
		if form.is_valid():
			blog=form.save(commit=False)
			blog.author=Profile.objects.get(user=request.user)
			im=Image.open(blog.img)
			#print type(blog.img)
			'''fn , fext = os.path.splitext(im)
			im2= im.convert('RGB')
			im2.save('demo.jpg')'''
			blog.save()
			#print im.filename
			#print fn + '\n' + fext
			context = {'post':get_object_or_404(Blog, slug=blog.slug),'image':blog.img }

			return render(request,'blog/view_post.html',context)
		
	else:
		form = PostForm()

	context={'form':form}
	return render(request, 'blog/post_edit.html',context)

def post_edit(request,slug):
	#print slug
	post = get_object_or_404(Blog, slug=slug)
	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			#print "YES"
			post = form.save(commit=False)
			post.date=timezone.now()
			post.save()
			context={'post':post, 'slug':post.slug}
			return render(request, 'blog/view_post.html', context)

	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html',{'form':form})

def logout_page(request):
	#View for logout page, it will perform the operations we need to perform
	#before the user is finally logged out.
	logout(request)
	return HttpResponseRedirect('/')


def register_page(request):
	if request.method=='POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user=User.objects.create_user(username=form.cleaned_data['username'], first_name=form.cleaned_data['first_name'],password=form.cleaned_data['password1'],email=form.cleaned_data['email'])
			auth_login(request,user)
			return HttpResponseRedirect('/blog')
	form=RegistrationForm()
	return render(request, 'registration/register.html', {'form':form})

def search(request):
	qlist=(Profile.objects.all())
	query=request.session['query']
	logged_in=request.user
	#print "qweoplksasdp;swiop"
	#query=(request.GET.get("q"))
	#print query
	if query:
		qlist = qlist.filter(user__username__icontains=query).filter(~Q(user=logged_in))
	qlist=list(qlist)
	list_names=[]
	pro=request.user
	a=0
	for i in qlist:
		list_names.append(i)
		
		a+=1
	if None:
		#print i.pk
		#print "Raghav"
		return redirect('blog:follow',pk=i.pk)
	context= {'list_names':list_names,'logged_in':pro}
	return render(request, 'blog/search.html', context)

def follow(request,pk):
	#print pk
	p=Profile.objects.get(pk=pk) #user we searched
	q= request.user #logged_in user
	#print q.username
	#print p.user.username
	p.followers.add(q)

	return redirect('blog:index')

def unfollow(request,pk):
	p=Profile.objects.get(pk=pk)
	q=request.user
	p.followers.remove(q)
	return redirect('blog:search')

def login(request):
	return redirect(auth_views.login)

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}My first blog{% endblock %}</title>
{% block static %}{% endblock %}    </head>
    <body>
        <h1>{% block title %}My first blog in django{% endblock %}</h1>
        <a href="{% url 'blog:post_new' %}" class="top-menu"></a>
        {% block content %}

        {% endblock %}
    </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}My first Blog in django{% endblock %}


{% block content %}
    <form method ='GET' action=''>
    <input type=text' name='q' placeholder='Search for other users'/>
    <input type="submit" value="SEARCH!!" />

  </form>
    <h4>Hello {{username}}</h4>
    <h2><a href="{% url 'blog:logout_page' %}">Logout</a></h2>
    <h1>Followers </h1>
    {% if followers %}
      <ul>
        {% for i in followers %}
        <li>  {{i}} </br></li>
        {% endfor %}

      </ul>
    {% else %}
      NONE
    {% endif %}
    <h1> Following </h1>
    {% if list %}
      <ul>
        {% for i in list %}
        <li> {{i.user.username}} </br> </li>
        {% endfor %}
      </ul>
    {% else %}
      None
    {% endif %}

    
    <h2>Posts</h2>
    <h2><a href="{%url 'blog:post_new' %}">Add a new Post</a></h2>
    {% if posts %}
        <ul>
        {% for post in posts %}
            {% if post.author == user_profile %}
            <h1><a href="{% url 'blog:view_post' slug=post.slug %}">{{post.title}}</a></h1>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <li>There are no posts.</li>
    {% endif %}

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <!--<h1>New post</h1>-->
    {% if post.date %}
            <div class="date">
                {{ post.published_date }}
            </div>

    {% endif %}
    <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
     <!--   Title :
		<input type = "text"> <br><br>
		Enter Content: <br>
		<textarea name="textarea" style="width:1200px;height:300px;"></textarea><br>
		Slug:
		<input type="text"><br>-->
		{{ form.as_p }}
        <button type="submit" class="save btn btn-default btn-lg">Save</button>
    </form>
{% endblock %}

blog/templates/blog/search.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head_title %}Search {% endblock %}</title>
    </head>
    <body>
        <h1>{% block title %}Search results:{% endblock %}</h1>
        <a href ='{%url 'blog:index' %}' /> Homepage</a>
        <ul>
        {% for name in list_names %}
            <form method='GET'>
              <h1>{{name.user.username}} {{name.pk}}
                {% if logged_in in name.followers.all %}
                  <a href='{%url 'blog:unfollow' pk=name.pk %}' /> Unfollow</a>
                {% else %}
                  <a href='{%url 'blog:follow' pk=name.pk %}' /> Follow</a>
                {% endif %}
            </h1>
            </form>

        {% endfor %}
        </ul>
        {% block content %}

        {% endblock %}
    </body>
</html>

blog/templates/blog/view_category.html
{% extends 'blog/base.html' %} 
{% block head_title %}Viewing category {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
	<h2>Categories</h2>
    {% if posts %}
        <ul>
        {% for post in posts %}
            <h1><a href="{% url 'blog:view_post' slug=post.slug %}">{{post.title}}</a></h1>
          
        {% endfor %}
        </ul>
    {% else %}
        <li>There are no posts.</li>
    {% endif %}
{% endblock %}

blog/templates/blog/view_post.html
{% extends 'blog/base.html' %}
{% block head_title %}{{ post.title }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}
{% block static %} {% endblock %}

{% block content %}
    {{ post.body }}
  <h4>Author:</h4>  <p>{{post.author.user.username}}</p>
  <img src={{image.url}} alt="Profile picture" >
    <a class="btn btn-default" href="{% url 'blog:post_edit' slug=post.slug %}"><br> EDIT</a>
    <br><br><a href='{% url 'blog:index' %}' /> Homepage </a>
{% endblock %}