blog/urls.py
from django.conf.urls import url,include
from . import views

app_name='blog'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^view/(?P<slug>[-\w]+)/$',views.view_post, name='view_post'),
	url(r'^category/(?P<slug>[-\w]+)/$',views.view_category, name='view_category'),
	url(r'^new$',views.post_new, name='post_new'),
	#url(r'accounts/', include('registration.backends.hmac.urls')),
	url(r'^post/(?P<slug>[-\w]+)$', views.post_edit, name='post_edit'),
	url(r'logout/$', views.logout_page,name='logout_page'),
	url(r'register/$',views.register_page,name='register_page'),
	url(r'search/$', views.search, name='search'),
	url(r'^follow/(?P<pk>[0-9]+)', views.follow,name='follow'),
	url(r'^unfollow/(?P<pk>[0-9]+)',views.unfollow, name='unfollow'),
	url(r'^login$', views.login, name='login'),
	#url(r'login/$', views.login_page, name='login_page'),
	]
#[^\.]       ?????
#study regular expressions again!

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    #url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$',views.default )
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models import permalink
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image
# Create your models here.

class Category(models.Model):
	title =models.CharField(max_length=100, db_index=True)
	slug =models.SlugField(max_length=100, db_index=True)
	#def __unicode__(self):
	#	return '%s' %self.title

	#@permalink
	#def get_absolute_url(self):
	#	return ('view_blog_category', None, {'slug':self.slug})

	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		super(Category, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

#Review this again!
class Profile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	birth_date=models.DateField(null=True, blank=True)
	followers=models.ManyToManyField(User,related_name='following',symmetrical=False)#list of followers


	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created :
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


class Blog(models.Model):
	title = models.CharField(max_length = 100, unique=True)
	slug = models.SlugField(max_length=100,unique = True)
	body = models.TextField()
	img=models.ImageField(upload_to='blog/blog/static/',null=True,help_text='Upload an image')
	posted =models.DateField(db_index = True, auto_now_add=True)
	category=models.ForeignKey('blog.Category', on_delete=models.CASCADE,default='1')
	date = models.DateTimeField(auto_now_add=True)
	update= models.DateTimeField(auto_now=True)
	author=models.ForeignKey(Profile,related_name='article',on_delete=models.CASCADE,default=1)

#revisit on_delete .
	#def __unicode__(self):
	#	return self.title

	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		super(Blog, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

	#@permalink
	#def get_absolute_url(self):
	#	return ('view_blog_post', None, {'slug':self.slug})

blog/forms.py
from django.forms import ModelForm
from django import forms
from blog.models import Blog
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class PostForm(ModelForm):

    class Meta:
        model = Blog
        fields = ['title','body','category']

class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    first_name=forms.CharField(label='First Name', max_length=20)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                          widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password (Again)',
                        widget=forms.PasswordInput())

    def clean_password2(self):
    	if 'password1' in self.cleaned_data:
    		password1=self.cleaned_data['password1']
    		password2=self.cleaned_data['password2']
    		if password1 == password2:
    			return password2
    	#raise forms.ValidationError('Passwords do not match')
    		else:
    			raise forms.ValidationError("passwords do not match")


    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        #raise forms.ValidationError('Username is already taken.')
        raise forms.ValidationError(('Username is already taken'), code='invalid')

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import PostForm,RegistrationForm
#from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Blog, Category,Profile
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic.detail import DetailView
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,authenticate, login as auth_login, views as auth_views
#from django.contrib.auth import login as auth_login
#from app.forms import *
#from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.db.models import Q
from PIL import Image
import os
#Django.contrib.auth  ---------  authenticate() to authenticate if the specific user is logged in

@login_required
def index(request):
	#print request.user.username
	#a=list(Profile.objects.all())
	#print a.username   --------------   WRONG!
#	print a[0].user.username	----------- RIGHT!
	if request.GET:
		query=(request.GET.get("q"))
		#print query
		request.session['query']=query
		return redirect('blog:search')


	q=request.user
	#tr=authenticate(username='raghav',password='bitspilani')
	a=Profile.objects.get(user=q)
	#u=authenticate()

	list_following=list(q.following.all())
	l=len(list_following)

	context={'l':l,'list':list_following,'categories':Category.objects.all(),'followers':list(a.followers.all()),'posts':Blog.objects.all(), 'username':request.user.username,'user_profile':a}
	return render(request,'blog/index.html', context)

@login_required
def view_post(request, slug):
	context = {'post':get_object_or_404(Blog, slug=slug)}

	return render(request,'blog/view_post.html',context)


def view_category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	context = {'category':category, 'posts':Blog.objects.filter(category = category)}
	return render(request,'blog/view_category.html', context)

@login_required
def post_new(request):

	if request.method=='POST':
		form =PostForm(request.POST,request.FILES)
		#print "IS_VALID"
		if form.is_valid():
			blog=form.save(commit=False)
			blog.author=Profile.objects.get(user=request.user)
			im=Image.open(blog.img)
			#print type(blog.img)
			'''fn , fext = os.path.splitext(im)
			im2= im.convert('RGB')
			im2.save('demo.jpg')'''
			blog.save()
			#print im.filename
			#print fn + '\n' + fext
			context = {'post':get_object_or_404(Blog, slug=blog.slug),'image':blog.img }

			return render(request,'blog/view_post.html',context)
		
	else:
		form = PostForm()

	context={'form':form}
	return render(request, 'blog/post_edit.html',context)

def post_edit(request,slug):
	#print slug
	post = get_object_or_404(Blog, slug=slug)
	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			#print "YES"
			post = form.save(commit=False)
			post.date=timezone.now()
			post.save()
			context={'post':post, 'slug':post.slug}
			return render(request, 'blog/view_post.html', context)

	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html',{'form':form})

def logout_page(request):
	#View for logout page, it will perform the operations we need to perform
	#before the user is finally logged out.
	logout(request)
	return HttpResponseRedirect('/')


def register_page(request):
	if request.method=='POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user=User.objects.create_user(username=form.cleaned_data['username'], first_name=form.cleaned_data['first_name'],password=form.cleaned_data['password1'],email=form.cleaned_data['email'])
			auth_login(request,user)
			return HttpResponseRedirect('/blog')
	form=RegistrationForm()
	return render(request, 'registration/register.html', {'form':form})

def search(request):
	qlist=(Profile.objects.all())
	query=request.session['query']
	logged_in=request.user
	#print "qweoplksasdp;swiop"
	#query=(request.GET.get("q"))
	#print query
	if query:
		qlist = qlist.filter(user__username__icontains=query).filter(~Q(user=logged_in))
	qlist=list(qlist)
	list_names=[]
	pro=request.user
	a=0
	for i in qlist:
		list_names.append(i)
		
		a+=1
	if None:
		#print i.pk
		#print "Raghav"
		return redirect('blog:follow',pk=i.pk)
	context= {'list_names':list_names,'logged_in':pro}
	return render(request, 'blog/search.html', context)

def follow(request,pk):
	#print pk
	p=Profile.objects.get(pk=pk) #user we searched
	q= request.user #logged_in user
	#print q.username
	#print p.user.username
	p.followers.add(q)

	return redirect('blog:index')

def unfollow(request,pk):
	p=Profile.objects.get(pk=pk)
	q=request.user
	p.followers.remove(q)
	return redirect('blog:search')

def login(request):
	return redirect(auth_views.login)

blog/templates/project/default.html

<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
<title>Welcome :)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Raghav Arora Break Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="{% static 'application/x-javascript' %}"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'js/jquery.min.js' %}"></script>
<!---- start-smoth-scrolling---->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
		</script>
<!--start-smoth-scrolling-->
	<!--script-->
	<script src="{% static 'js/modernizr.custom.97074.js' %}"></script>
<script src="{% static 'js/jquery.chocolat.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/chocolat.css' %}" type="text/css" media="screen" charset="utf-8">
		<!--light-box-files -->
		<script type="text/javascript" charset="utf-8">
		$(function() {
			$('.gallery a').Chocolat();
		});
		</script>
		<script type="text/javascript" src="{% static 'js/jquery.hoverdir.js' %}"></script>
</head>
<body>
	<!--header-top-starts-->
	<div class="header-top">
		<div class="container">
			<div class="head-main">
				<a ><img src="{% static 'images/logo-1.png' %}" alt="" /></a>
			</div>
		</div>
	</div>
	<!--header-top-end-->
	<!--start-header-->
	<div class="header">
		<div class="container">
			<div class="head">
			<div class="navigation">
				 <span class="menu"></span>
					<ul class="navig">
						<li><a href="{% url 'blog:login' %}">Login</a></li>
						<li><a href="{%url 'blog:register_page' %}">Create a new account</a></li>
						
					</ul>
			</div>
			<div class="header-right">
				<div class="search-bar">
					<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					<input type="submit" value="">
				</div>
				<ul>
					<li><a href="#"><span class="fb"> </span></a></li>
					<li><a href="#"><span class="twit"> </span></a></li>
					<li><a href="#"><span class="pin"> </span></a></li>
					<li><a href="#"><span class="rss"> </span></a></li>
					<li><a href="#"><span class="drbl"> </span></a></li>
				</ul>
			</div>
				<div class="clearfix"></div>
			</div>
			</div>
		</div>
	<!-- script-for-menu -->
	<!-- script-for-menu -->
		<script>
			$("span.menu").click(function(){
				$(" ul.navig").slideToggle("slow" , function(){
				});
			});
		</script>
	<!-- script-for-menu -->
	<!--banner-starts-->
	<div class="banner">
		<div class="container">
			<div class="banner-top">
				<div class="banner-text">
					<h2>Raghav Arora</h2>
					<h1>Blog</h1>

				</div>
			</div>
		</div>
	</div>
	<!--banner-end-->
	<!--gallery-starts-->
	<div class="gallery">
		<div class="container">
			<div class="gallery-top heading">
				<h3>Welcome _/\_</h3>
			</div>
			
		<script type="text/javascript">
			$(function() {

				$(' #da-thumbs > li ').each( function() { $(this).hoverdir(); } );

			});
		</script>
        </div>
	</div>
	<!--gallery-end-->
	<!--footer-starts-->
	<div class="footer">
		<div class="container">
			<div class="footer-text">
				<p>©  Raghav Arora Ji. No Rights Reserved  </p>
			</div>
		</div>
	</div>
	<!--footer-end-->
</body>
</html>